from .skeleton_magnitude_representation import SkeletonMagnitudeRepresentation
from .skeleton_dml_representation import SkeletonDMLRepresentation
from .sl_dml_representation import SlDMLRepresentation
from .base_image_representation import BaseImageRepresentation
